import streamlit as st
import pandas as pd

# --- Overview page for the VAT section ---
st.title("VAT Section — Quick Overview")
st.markdown("""
This page provides a concise summary of each module in the VAT section so
you can quickly understand the scope and jump to the detailed pages.
""")

modules = [
    ("Introduction", "Core features of VAT, legislative framework and a high-level view of rates."),
    ("Statutory Definitions", "Key legal definitions used throughout the VAT system (economic activity, input, time of supply, etc.)."),
    ("Registration & Enlistment", "Thresholds, mandatory vs voluntary registration, central vs unit registration and BIN rules."),
    ("Imposition of VAT & SD", "Scope of taxable supplies, valuation rules, and interaction with Supplementary Duty."),
    ("Manner of Collection", "Collection points: imports, domestic invoicing, withholding (VDS) and timing of payment."),
    ("Net Tax Payable", "Self-assessment formula, calculation flow and payment/filing deadlines."),
    ("Input Tax Credit (ITC)", "Entitlement conditions, required documentation, limitation periods and partial credit rules."),
    ("Withholding VAT (VDS)", "VDS schedules, service codes, certificate (Mushak-6.6) rules and compliance."),
    ("Carry Forward & Refunds", "Handling negative net amounts: carry-forward mechanics and refund application process."),
    ("Supplementary Duty (SD)", "Scope, common rates, valuation for SD and its non-creditable nature."),
    ("Books & Records", "Mandatory registers, Mushak forms and retention/audit-readiness requirements."),
    ("Submission of Returns", "Return types (Mushak-9.1/9.2), deadlines, amendments and penalties for late filing."),
    ("Penalties & Consequences", "Monetary penalties, interest, BIN suspension and operational impacts."),
    ("Recovery of Arrears", "NBR recovery powers including garnishment, seizure and import/export blocks."),
    ("Audit & Investigation", "Audit triggers, key focus areas and the audit cycle and verification procedures."),
    ("Offences & Punishment", "Criminal offences, trial procedures and corporate/management liability."),
    ("Appeals & Revisions", "Appellate hierarchy, mandatory deposits, ADR options and timelines."),
    ("Annexures & Tables", "Reference tables: Mushak form summary, VAT rates and VAT vs Turnover Tax comparisons.")
]

df = pd.DataFrame(modules, columns=["Module", "Brief Summary"])

st.dataframe(df, use_container_width=True)

st.markdown("---")
st.subheader("How to use")
st.markdown("- Read the brief summary to find the relevant module.\n- Open the corresponding file in the `04_VAT` folder for full details.\n- Ask me to refine any summary or add cross-links to the homepage.")

st.markdown("<center style='font-size:0.85rem;color:#9CA3AF;'>Overview autogenerated — edit `00_VAT_Overview.py` to customize.</center>", unsafe_allow_html=True)
