import streamlit as st

# --- DO NOT CALL set_page_config HERE (Handled by Homepage) ---

# --- STANDARD WEBPAGE STYLING ---
st.markdown("""
    <style>
    html, body, [class*="st-"] {
        font-size: 16px;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    }
    h1 { font-size: 2.1rem !important; color: #1E3A8A !important; }
    h2 { font-size: 1.6rem !important; color: #1E40AF !important; margin-top: 1.5rem !important; }
    h3 { font-size: 1.25rem !important; color: #1E40AF !important; }
    p, li { font-size: 1rem !important; line-height: 1.6; color: #374151; }
    
    .document-card {
        background-color: #f8fafc;
        padding: 15px;
        border-radius: 8px;
        border-left: 5px solid #1E3A8A;
        margin-bottom: 12px;
        box-shadow: 0 1px 3px rgba(0,0,0,0.05);
    }
    .mushak-label {
        font-weight: bold;
        color: #1E3A8A;
        background-color: #e2e8f0;
        padding: 2px 6px;
        border-radius: 4px;
        font-size: 0.9rem;
    }
    </style>
    """, unsafe_allow_html=True)

# --- SIDEBAR ---
st.sidebar.header("Record Keeping")
st.sidebar.info("Section 107: Failure to maintain these records can lead to a Tk. 50,000 penalty per instance.")

# --- HEADER ---
st.title("Books and Documents for VAT")
st.markdown("#### Sections 107-108 | VAT & SD Act, 2012")
st.divider()

# --- 1. MANDATORY REGISTERS ---
st.subheader("📋 Primary VAT Registers")
st.markdown("These registers must be updated in real-time as transactions occur.")

col1, col2 = st.columns(2)

with col1:
    st.markdown(f"""
    <div class="document-card">
        <span class="mushak-label">Mushak-6.1</span>
        <p><b>Purchase Register:</b> Records all local and import purchases of raw materials, packing materials, and services.</p>
    </div>
    """, unsafe_allow_html=True)

with col2:
    st.markdown(f"""
    <div class="document-card">
        <span class="mushak-label">Mushak-6.2</span>
        <p><b>Sales Register:</b> Records all sales and supplies. Must be updated <i>before</i> the goods are removed from the premises.</p>
    </div>
    """, unsafe_allow_html=True)

# --- 2. TRANSACTIONAL DOCUMENTS ---
st.subheader("📄 Mandatory Forms & Invoices")

with st.expander("The Standard Tax Invoice (Mushak-6.3)"):
    st.write("""
    This is the most important document in the VAT system. It must contain:
    * Name, Address, and 13-digit BIN of the Supplier.
    * Name, Address, and 13-digit BIN of the Buyer (for purchases > Tk. 25,000).
    * Description, Quantity, and Value of goods/services.
    * Amount of VAT and SD charged.
    """)

with st.expander("Adjustment Documents (6.7 & 6.8)"):
    st.write("**Mushak-6.7 (Credit Note):** Issued by the supplier when the price decreases or goods are returned.")
    st.write("**Mushak-6.8 (Debit Note):** Issued by the supplier when the price increases after the initial invoice.")

with st.expander("VDS Certificate (Mushak-6.6)"):
    st.write("Mandatory for taking a decreasing adjustment when VAT is deducted at source by a withholding entity.")

# --- 3. RETENTION & AUDIT ---
st.subheader("⚖️ Legal Requirements")
st.markdown("""
* **Retention:** You must keep these records for **5 years**.
* **Accessibility:** If a VAT officer visits the factory, these books must be produced immediately.
* **Format:** Can be manual or electronic (if the software is NBR-approved).
""")

# --- FOOTER ---
st.divider()
st.info("""
**💡 Finance Lead Note:** In a high-volume factory, manual '6.1' and '6.2' registers 
are prone to error. Ensure your ERP (SAP/Oracle) is properly mapped so that the 
**Mushak-6.3** generated by the system pulls the correct **Service Codes** and 
tax rates. During a 'Post Clearance Audit', the NBR will cross-verify your 
inventory ledgers against your **Mushak-6.1**—any discrepancy usually results in a 
demand for unpaid VAT.
""")

st.markdown("<center style='font-size: 0.85rem; color: #9CA3AF;'>Knowledge Folder | Books & Records Module © 2026</center>", unsafe_allow_html=True)