"""
================================================================================
APPLIED FINANCIAL MODELS
Module 1.3 — CASH FLOW STATEMENT MODELING
================================================================================

A single-page, interactive Streamlit module that teaches finance professionals
how to model the cash flow statement using the INDIRECT method, and how it links
the income statement and balance sheet together.

The page follows the standard 5-tab structure used across the site:
    1. Theory & Concepts
    2. Worked Examples
    3. Interactive Exercises   (a live indirect-method cash flow builder)
    4. Real-Life Practical Cases
    5. Knowledge Test / Quiz

--------------------------------------------------------------------------------
HOW TO RUN
--------------------------------------------------------------------------------
    pip install streamlit pandas
    streamlit run Module_1_3_Cash_Flow_Statement_Modeling.py
================================================================================
"""

from datetime import datetime

import pandas as pd
import streamlit as st

st.set_page_config(
    page_title="1.3 Cash Flow Statement Modeling — Applied Financial Models",
    layout="wide",
    page_icon="🏛️",
)

# --------------------------------------------------------------------------------
# HELPERS
# --------------------------------------------------------------------------------
def money(x, symbol="€", dp=0):
    sign = "-" if x < 0 else ""
    return f"{sign}{symbol}{abs(x):,.{dp}f}"


# --------------------------------------------------------------------------------
# SIDEBAR
# --------------------------------------------------------------------------------
st.sidebar.title("⚙️ Module Control Panel")
st.sidebar.caption("Part 1 · The Three-Statement Model")
st.sidebar.markdown(
    """
**Module 1.3 — Cash Flow Statement Modeling**

🟡 *Intermediate*

**You will learn to:**
- Build a cash flow statement (indirect method)
- Reconcile net income to actual cash
- Split cash flow into Operating / Investing / Financing
- Link cash flow to the P&L and balance sheet
"""
)
st.sidebar.markdown("---")
st.sidebar.info(
    "💡 Head to the **Interactive Exercises** tab to build a live cash flow "
    "statement and see how profit turns into real cash."
)
st.sidebar.markdown("---")
st.sidebar.caption("Applied Financial Models · Understand → Build → Interpret → Decide")

# --------------------------------------------------------------------------------
# HEADER
# --------------------------------------------------------------------------------
st.title("🏛️ 1.3 · Cash Flow Statement Modeling")
st.markdown(
    """
Profit is an opinion; **cash is a fact**. The income statement can show a healthy profit while the bank
balance falls — because profit includes non-cash items and ignores the timing of cash in and out. The
**cash flow statement** bridges that gap, showing exactly how the cash balance moved over the period.

This module focuses on the **indirect method** — the approach used in virtually all financial models —
which starts from net income and adjusts it back to real cash.
"""
)

c1, c2, c3, c4 = st.columns(4)
c1.metric("Module", "1.3")
c2.metric("Part", "1 — 3-Statement")
c3.metric("Level", "Intermediate")
c4.metric("Learning Tabs", "5")

tab_labels = [
    "📚 Theory & Concepts",
    "🔢 Worked Examples",
    "✏️ Interactive Exercises",
    "🏭 Real-Life Practical Cases",
    "✅ Knowledge Test / Quiz",
]
tabs = st.tabs(tab_labels)

# ================================================================================
# TAB 1 — THEORY & CONCEPTS
# ================================================================================
with tabs[0]:
    st.subheader("Theory & Concepts")

    st.markdown(
        """
### The three sections of a cash flow statement
Every cash flow statement splits movements into three activities, then ties to the change in cash:
"""
    )

    sections = pd.DataFrame(
        {
            "Section": ["Cash Flow from Operations (CFO)", "Cash Flow from Investing (CFI)",
                        "Cash Flow from Financing (CFF)"],
            "Captures": [
                "Cash generated by the core business (day-to-day trading)",
                "Buying/selling long-term assets (capex, acquisitions, disposals)",
                "Raising/repaying capital (debt draws & repayments, equity, dividends)",
            ],
            "Typical items": [
                "Net income, + depreciation, ± working capital changes",
                "− Capex, − acquisitions, + asset sales",
                "+ New debt, − repayments, + equity issued, − dividends",
            ],
        }
    )
    st.table(sections)

    st.markdown(
        """
### The indirect method (start from profit, adjust to cash)
The indirect method builds **Cash Flow from Operations** like this:
"""
    )
    st.latex(r"CFO = \text{Net Income} + \text{Depreciation} \pm \Delta\text{Working Capital}")

    st.markdown(
        """
Then the full statement reconciles to the movement in cash:

$$\\Delta\\text{Cash} = CFO + CFI + CFF$$

$$\\text{Closing Cash} = \\text{Opening Cash} + \\Delta\\text{Cash}$$
"""
    )

    with st.expander("🔑 Concept 1 — Add back non-cash items (depreciation)"):
        st.markdown(
            """
Depreciation was subtracted on the income statement, but **no cash actually left** the business — it's
an accounting allocation of past capex. So we **add it back** to net income. The same applies to
amortisation and other non-cash charges.

> Net income understates cash by the amount of non-cash charges — adding them back corrects this.
"""
        )

    with st.expander("🔑 Concept 2 — Working capital changes (the timing effect)"):
        st.markdown(
            """
Changes in working capital move cash **opposite** to the balance-sheet change:

| If this goes UP… | Effect on cash |
|---|---|
| Receivables ↑ (customers owe more) | Cash ↓ (uses cash) |
| Inventory ↑ (more stock held) | Cash ↓ (uses cash) |
| Payables ↑ (you owe suppliers more) | Cash ↑ (source of cash) |

$$\\Delta WC = \\Delta\\text{Receivables} + \\Delta\\text{Inventory} - \\Delta\\text{Payables}$$

An **increase** in net working capital **consumes** cash (subtract it); a decrease releases cash.
"""
        )

    with st.expander("🔑 Concept 3 — Capex sits in Investing, not Operating"):
        st.markdown(
            """
Buying equipment is a real cash outflow, but it belongs in **Investing (CFI)**, not Operations. This
separation lets readers see whether the *core business* generates cash (CFO) before the effects of
investment and financing decisions.

**Free Cash Flow (FCF)** = CFO − Capex — a key measure used throughout valuation (Part 3).
"""
        )

    with st.expander("🔑 Concept 4 — How cash flow links the three statements"):
        st.markdown(
            """
The cash flow statement is the **glue** of the three-statement model:
- **Net income** comes from the *income statement*.
- **Depreciation, working-capital changes, capex, debt & dividends** come from the *balance sheet* movements.
- The **closing cash** it calculates flows straight back onto the *balance sheet*.

If everything is linked correctly, the balance sheet balances automatically (see Module 1.4).
"""
        )

    st.success(
        "**Takeaway:** The indirect method starts from net income, adds back non-cash items, adjusts for "
        "working-capital timing, then layers investing and financing flows to explain the change in cash."
    )

# ================================================================================
# TAB 2 — WORKED EXAMPLES
# ================================================================================
with tabs[1]:
    st.subheader("Worked Example — From profit to cash, step by step")
    st.markdown("Continuing our fictional company **'CleanSoap'** from the previous modules.")

    st.markdown("#### Starting point (from the income statement & balance sheet)")
    st.markdown(
        """
| Item | Value |
|---|---|
| Net income | €231,000 |
| Depreciation (non-cash) | €120,000 |
| Increase in receivables | €46,575 |
| Increase in inventory | €27,260 |
| Increase in payables | €18,630 |
| Capex | €200,000 |
| New long-term debt | €100,000 |
| Dividends paid | €50,000 |
| Opening cash | €150,000 |
"""
    )

    st.markdown("#### Step 1 — Cash Flow from Operations (indirect method)")
    st.markdown(
        """
| Line | Calculation | € |
|---|---|---|
| Net income | | 231,000 |
| + Depreciation | add back non-cash | 120,000 |
| − Increase in receivables | uses cash | (46,575) |
| − Increase in inventory | uses cash | (27,260) |
| + Increase in payables | source of cash | 18,630 |
| **= Cash Flow from Operations** | | **€295,795** |
"""
    )

    st.markdown("#### Step 2 — Investing & Financing")
    st.markdown(
        """
| Section | Item | € |
|---|---|---|
| **Investing (CFI)** | − Capex | (200,000) |
| **Financing (CFF)** | + New debt | 100,000 |
| | − Dividends | (50,000) |
| | **CFF subtotal** | **50,000** |
"""
    )

    st.markdown("#### Step 3 — Reconcile to closing cash")
    col1, col2, col3 = st.columns(3)
    col1.metric("CFO", "€295,795")
    col2.metric("CFI", "-€200,000")
    col3.metric("CFF", "€50,000")

    st.markdown(
        """
$$\\Delta\\text{Cash} = 295{,}795 - 200{,}000 + 50{,}000 = \\mathbf{€145{,}795}$$
$$\\text{Closing Cash} = 150{,}000 + 145{,}795 = \\mathbf{€295{,}795}$$
"""
    )

    st.info(
        "**Insight:** Net income was €231k, but the business actually generated **€296k of operating cash** "
        "(thanks to the €120k depreciation add-back), and ended with €296k cash despite spending €200k on "
        "capex. **This is why profit ≠ cash** — and why the cash flow statement is essential."
    )

# ================================================================================
# TAB 3 — INTERACTIVE EXERCISES
# ================================================================================
with tabs[2]:
    st.subheader("✏️ Interactive Exercise — Build a Cash Flow Statement (Indirect Method)")
    st.markdown(
        "Adjust the drivers on the left. Watch net income get converted into **real cash**, split across "
        "Operating, Investing and Financing — and see the closing cash balance update live."
    )

    left, right = st.columns([0.34, 0.66])

    with left:
        st.markdown("##### 🧾 From the P&L")
        net_income = st.number_input("Net income (€)", -1_000_000, 5_000_000, 231_000, 10_000)
        depreciation = st.number_input("Depreciation (add-back) (€)", 0, 2_000_000, 120_000, 10_000)

        st.markdown("##### 💧 Working capital changes")
        d_receivables = st.number_input("Δ Receivables (€)", -1_000_000, 1_000_000, 46_575, 5_000,
                                        help="Increase = uses cash")
        d_inventory = st.number_input("Δ Inventory (€)", -1_000_000, 1_000_000, 27_260, 5_000,
                                     help="Increase = uses cash")
        d_payables = st.number_input("Δ Payables (€)", -1_000_000, 1_000_000, 18_630, 5_000,
                                    help="Increase = source of cash")

        st.markdown("##### 🏭 Investing")
        capex = st.number_input("Capex (€)", 0, 5_000_000, 200_000, 25_000)
        asset_sales = st.number_input("Asset sales (€)", 0, 5_000_000, 0, 25_000)

        st.markdown("##### 🏦 Financing")
        new_debt = st.number_input("New debt raised (€)", 0, 10_000_000, 100_000, 25_000)
        debt_repay = st.number_input("Debt repayments (€)", 0, 10_000_000, 0, 25_000)
        equity_issued = st.number_input("Equity issued (€)", 0, 10_000_000, 0, 25_000)
        dividends = st.number_input("Dividends paid (€)", 0, 5_000_000, 50_000, 10_000)

        st.markdown("##### 🏁 Opening position")
        opening_cash = st.number_input("Opening cash (€)", -1_000_000, 10_000_000, 150_000, 10_000)

    with right:
        # CFO (indirect)
        cfo = net_income + depreciation - d_receivables - d_inventory + d_payables
        # CFI
        cfi = -capex + asset_sales
        # CFF
        cff = new_debt - debt_repay + equity_issued - dividends
        # Reconcile
        net_change = cfo + cfi + cff
        closing_cash = opening_cash + net_change
        fcf = cfo - capex

        k1, k2, k3 = st.columns(3)
        k1.metric("Operating (CFO)", money(cfo))
        k2.metric("Investing (CFI)", money(cfi))
        k3.metric("Financing (CFF)", money(cff))

        k4, k5, k6 = st.columns(3)
        k4.metric("Net change in cash", money(net_change))
        k5.metric("Closing cash", money(closing_cash),
                  "⚠️ Negative!" if closing_cash < 0 else None,
                  delta_color="inverse" if closing_cash < 0 else "normal")
        k6.metric("Free Cash Flow", money(fcf), help="CFO − Capex")

        if closing_cash < 0:
            st.error(
                f"⚠️ **Closing cash is negative ({money(closing_cash)}).** The business would run out of cash "
                "— it needs more financing, lower capex, or better working-capital management."
            )
        elif cfo < 0:
            st.warning(
                "🔎 **Operating cash flow is negative** — the core business is burning cash before any "
                "investment or financing. Watch this closely."
            )
        else:
            st.success(f"✅ Healthy: the business generated **{money(cfo)}** of operating cash this period.")

        # Statement table
        cf = pd.DataFrame(
            {
                "Cash Flow Statement (Indirect Method)": [
                    "Net income",
                    "  + Depreciation (non-cash)",
                    "  − Δ Receivables",
                    "  − Δ Inventory",
                    "  + Δ Payables",
                    "= Cash Flow from Operations (CFO)",
                    "  − Capex",
                    "  + Asset sales",
                    "= Cash Flow from Investing (CFI)",
                    "  + New debt",
                    "  − Debt repayments",
                    "  + Equity issued",
                    "  − Dividends",
                    "= Cash Flow from Financing (CFF)",
                    "Net change in cash",
                    "Opening cash",
                    "= Closing cash",
                ],
                "€": [
                    net_income, depreciation, -d_receivables, -d_inventory, d_payables, cfo,
                    -capex, asset_sales, cfi,
                    new_debt, -debt_repay, equity_issued, -dividends, cff,
                    net_change, opening_cash, closing_cash,
                ],
            }
        )
        cf["€"] = cf["€"].map(lambda v: money(v))
        st.markdown("##### 📄 Cash Flow Statement")
        st.dataframe(cf, use_container_width=True, hide_index=True)

    st.markdown("---")
    st.markdown("##### 🧪 Try these challenges")
    e1, e2 = st.columns(2)
    with e1:
        st.markdown(
            """
1. **Profit ≠ cash:** Set net income to €231k but push Δ Receivables to €400k. Watch CFO turn negative
   despite a healthy profit.
2. **Depreciation add-back:** Raise depreciation to €500k. See CFO rise even though profit is unchanged.
"""
        )
    with e2:
        st.markdown(
            """
3. **Capex crunch:** Push capex to €1,000,000. Does closing cash go negative? How would you fund the gap?
4. **Free cash flow:** Find the combination where FCF (CFO − Capex) is exactly zero.
"""
        )

    st.download_button(
        "⬇️ Download this cash flow statement (CSV)",
        cf.to_csv(index=False).encode("utf-8"),
        "cash_flow_statement.csv",
        "text/csv",
    )

# ================================================================================
# TAB 4 — REAL-LIFE PRACTICAL CASES
# ================================================================================
with tabs[3]:
    st.subheader("🏭 Real-Life Practical Cases")

    with st.expander("Case A — The profitable company that went bust (cash is king)", expanded=True):
        st.markdown(
            """
**Situation:** A rapidly growing distributor reported strong profits every quarter — then suddenly
couldn't pay its suppliers and collapsed.

**What the cash flow statement revealed:** Explosive sales growth meant receivables and inventory
soared, so **operating cash flow was deeply negative** even though the P&L showed profit. Growth was
consuming cash faster than it earned it.

**Why it matters:** A cash flow model would have flagged the negative CFO quarters in advance, giving
time to arrange financing or slow growth.

**Lesson:** Companies don't fail because they're unprofitable — they fail because they run out of cash.
"""
        )

    with st.expander("Case B — Depreciation and the 'hidden' operating cash"):
        st.markdown(
            """
**Situation:** A capital-intensive manufacturer showed modest net income, worrying the board.

**What the cash flow statement revealed:** A large **depreciation add-back** meant operating cash flow
was far stronger than net income suggested — the business was generating plenty of cash to reinvest
and service debt.

**Why it matters:** Focusing only on net income understated the company's true cash-generating power.

**Lesson:** For asset-heavy businesses, CFO (not net income) is often the truer measure of health.
"""
        )

    with st.expander("Case C — Free cash flow for a valuation"):
        st.markdown(
            """
**Situation:** An analyst valuing a business needed the cash available to all investors.

**How the cash flow statement helped:** **Free Cash Flow = CFO − Capex** provided the cash the business
throws off after maintaining its asset base — the exact input a DCF valuation discounts (Part 3).

**Why it matters:** Valuation is built on *cash*, not accounting profit, so a reliable cash flow model
is the foundation of any credible valuation.

**Lesson:** The cash flow statement isn't just a report — it feeds directly into investment and
valuation decisions.
"""
        )

    st.info(
        "🔗 **Pattern:** The cash flow statement turns accounting profit into the cash reality that drives "
        "survival, funding, and valuation. It's where the three statements — and real business risk — meet."
    )

# ================================================================================
# TAB 5 — KNOWLEDGE TEST / QUIZ
# ================================================================================
with tabs[4]:
    st.subheader("✅ Knowledge Test")
    st.markdown("Answer the questions below and click **Submit** for instant scoring and feedback.")

    with st.form("quiz_13"):
        q1 = st.radio(
            "**1.** The indirect method builds operating cash flow by starting from:",
            [
                "Revenue",
                "Net income, then adjusting for non-cash items and working capital",
                "Closing cash",
                "Total assets",
            ],
            index=None,
        )
        q2 = st.radio(
            "**2.** Why is depreciation ADDED BACK in the cash flow statement?",
            [
                "Because it increases net income",
                "Because it is a non-cash expense — no cash actually left the business",
                "Because it is a financing activity",
                "Because it is the same as capex",
            ],
            index=None,
        )
        q3 = st.radio(
            "**3.** An INCREASE in accounts receivable has what effect on cash?",
            [
                "Increases cash (a source of cash)",
                "Decreases cash (a use of cash)",
                "No effect on cash",
                "Increases net income",
            ],
            index=None,
        )
        q4 = st.radio(
            "**4.** Capex (buying equipment) appears in which section?",
            [
                "Operating activities",
                "Investing activities",
                "Financing activities",
                "It is never shown in the cash flow statement",
            ],
            index=None,
        )
        q5 = st.radio(
            "**5.** Free Cash Flow is best defined as:",
            [
                "Net income + dividends",
                "Cash Flow from Operations − Capex",
                "Revenue − COGS",
                "Closing cash − Opening cash",
            ],
            index=None,
        )

        submitted = st.form_submit_button("Submit answers")

    if submitted:
        answers = {
            "1": (q1, "Net income, then adjusting for non-cash items and working capital"),
            "2": (q2, "Because it is a non-cash expense — no cash actually left the business"),
            "3": (q3, "Decreases cash (a use of cash)"),
            "4": (q4, "Investing activities"),
            "5": (q5, "Cash Flow from Operations − Capex"),
        }
        score = sum(1 for _, (given, correct) in answers.items() if given == correct)

        st.markdown(f"### Your score: **{score} / 5**")
        if score == 5:
            st.balloons()
            st.success("Excellent — you've mastered cash flow modeling! On to Module 1.4 (Integrating the Model). 🎉")
        elif score >= 3:
            st.info("Good work — review the feedback below to close the gaps.")
        else:
            st.warning("Worth another pass — revisit the Theory tab, then retry.")

        st.markdown("#### Feedback")
        for qn, (given, correct) in answers.items():
            if given == correct:
                st.markdown(f"- **Q{qn}: ✅ Correct**")
            elif given is None:
                st.markdown(f"- **Q{qn}: ⚠️ Not answered.** Correct answer: _{correct}_")
            else:
                st.markdown(f"- **Q{qn}: ❌ Incorrect.** Correct answer: _{correct}_")

st.markdown("---")
st.caption(
    f"Applied Financial Models · Module 1.3 Cash Flow Statement Modeling · "
    f"Generated {datetime.now().strftime('%Y-%m-%d')} · "
    "Understand → Build → Interpret → Decide."
)
