import streamlit as st

# --- SUBPAGE HEADER ---
st.subheader("IFRS 13: Fair Value Measurement")
st.write("This standard defines fair value, sets out a framework for measuring fair value, and requires disclosures about fair value measurements.")

# --- THE CORE DEFINITION ---
st.info("**Definition:** Fair value is the price that would be received to sell an asset or paid to transfer a liability in an **orderly transaction** between market participants at the **measurement date**.")

# --- MAIN CONTENT TABS ---
tab1, tab2, tab3 = st.tabs(["Measurement Principles", "The 3-Level Hierarchy", "Valuation Techniques"])

with tab1:
    st.markdown("#### 1. Key Measurement Concepts")
    st.write("To measure fair value, an entity must determine the following:")
    
    col1, col2 = st.columns(2)
    with col1:
        st.success("**The Principal Market**")
        st.write("The market with the greatest volume and level of activity for the asset or liability.")
    with col2:
        st.success("**Most Advantageous Market**")
        st.write("The market that maximizes the amount received (if no principal market exists).")

    st.divider()
    st.markdown("#### Highest and Best Use (Non-Financial Assets)")
    st.write("For assets like land or buildings, fair value takes into account a market participant's ability to generate economic benefits by using the asset in its **highest and best use**.")
    st.caption("Example: A factory site might be worth more if converted into a residential complex.")

with tab2:
    st.markdown("#### 2. The Fair Value Hierarchy")
    st.write("IFRS 13 establishes a three-level hierarchy to increase consistency and comparability in fair value measurements.")

    st.error("**Level 1: Quoted Prices (Highest Reliability)**")
    st.write("Unadjusted quoted prices in active markets for identical assets or liabilities (e.g., Stock Exchange prices).")

    st.warning("**Level 2: Observable Inputs**")
    st.write("Inputs other than quoted prices included within Level 1 that are observable, either directly or indirectly (e.g., interest rates, yield curves).")

    st.info("**Level 3: Unobservable Inputs (Lowest Reliability)**")
    st.write("Inputs that are not based on observable market data. This requires management's own assumptions about what market participants would use (e.g., a DCF model for a private company).")

    

with tab3:
    st.markdown("#### 3. Valuation Techniques")
    st.write("An entity shall use valuation techniques that are appropriate in the circumstances and for which sufficient data are available.")
    
    c1, c2, c3 = st.columns(3)
    with c1:
        st.markdown("**Market Approach**")
        st.caption("Uses prices and other relevant information generated by market transactions involving identical or comparable assets.")
    with c2:
        st.markdown("**Cost Approach**")
        st.caption("Reflects the amount that would be required currently to replace the service capacity of an asset (Current Replacement Cost).")
    with c3:
        st.markdown("**Income Approach**")
        st.caption("Converts future amounts (cash flows or income) to a single current (discounted) amount (e.g., Present Value techniques).")

    st.divider()
    with st.expander("📝 Disclosure Requirements"):
        st.write("For Level 3 measurements, entities must provide a reconciliation from the opening to the closing balances and a description of the valuation processes used.")

# --- SIDEBAR CAPTION ---
st.sidebar.caption("Reference: International Financial Reporting Standard 13")